### ISSUE TITLE
All Chest upper lid cannot be closed

### ISSUE THREAD

**Issue by qwe938775** [OmerBenGera/WildChests#1]
There is a problem that bothers me...
All Chest upper lid cannot be closed
The video is as follows
Just tested that placing the item Frame & Funnel will not close the shell
After testing, just align the SHIFT and place the items on or around the box
The lid will not close

https://youtu.be/oTTR4naoyhQ

 suggest turning on the sound effect of the chest

**Comment by OmerBenGera** [comment]
Hey, sorry for the long waiting time.
Check out build #9 - let me know if it works for you

**Comment by qwe938775** [comment]
Normal use, you are great

**Comment by OmerBenGera** [comment]
Perfect :)
