### ISSUE TITLE
ChestShop duplication glitch remains

### ISSUE THREAD

**Issue by levtey** [OmerBenGera/WildChests#3]
By creating the chest shop not directly on the storage unit (putting the sign on the block above, for example) still allows you to create the chest shop and duplicate items.
![2021-01-21_16 46 48](https://user-images.githubusercontent.com/60494179/105430427-52962f00-5c08-11eb-9369-7391d03702ec.png)

**Comment by OmerBenGera** [comment]
I didnt know its possible - I will check it out

**Comment by OmerBenGera** [comment]
Fixed in build #10
