### ISSUE TITLE
Spawner Lag

### ISSUE THREAD

**Issue by levtey** [OmerBenGera/WildChests#5]
After updating from build 5 to the latest dev build (10), spawners are constantly taking a huge amount of the server tick, increasing with server uptime. Of all things, I wouldn't expect this plugin to affect them, but it seems like it started happening right after I updated. It starts off at 10 or so % of the server's total tick, and at some point has gone all the way up to using 50% of the CPU.
![image](https://user-images.githubusercontent.com/60494179/105606291-58495d00-5d4d-11eb-9e33-b5ee1600351c.png)

**Comment by OmerBenGera** [comment]
This has nothing to do with WildChests
