### ISSUE TITLE
ChestSort

### ISSUE THREAD

**Issue by mfnalex** [OmerBenGera/WildChests#9]
Hi, I am the author of ChestSort and I got a request to make ChestSort compatible with your plugin. Instead of using "null" as InventoryHolder, could you create a custom class to use instead, or use the ChestSortAPI and use an instance of `Sortable` as Holder? (See here: https://github.com/JEFF-Media-GbR/Spigot-ChestSort/blob/master/HOW_TO_USE_API.md#making-custom-inventories-sortable)

If you are simply using "null", there is no way for ChestSort to detect your custom inventories.

**Comment by OmerBenGera** [comment]
I don't see how it can work with WC, as it will force everyone to have the chests sorted all the time...

**Comment by mfnalex** [comment]
Every user can enable/disable automatic sorting or use hotkeys to sort...

**Comment by OmerBenGera** [comment]
I don't see how it can work with WildChests without forcing anybody to use it.
Your customer can fork WildChests and create his own version with support for your plugin
